# lib/boot.sh — /usr/local/bin/rpi-ap-boot.sh 생성
#
# 부팅 시 systemd가 실행할 스크립트를 동적으로 만든다.
# heredoc 안의 ${VAR} 은 setup.sh 시점에 치환, \$VAR 은 부팅 시점에 평가.

generate_boot_script() {
    # --- 헤더 + NM/wpa 정리 + STA 측 설정 ---
    sudo tee /usr/local/bin/rpi-ap-boot.sh > /dev/null <<EOF
#!/bin/bash
# Auto-generated by setup.sh — RPi #${HOP}

AP_IF="${AP_IF}"
AP_IP="${AP_IP}"
STA_IF="${STA_IF}"
HOP="${HOP}"
STA_STATIC_IP="$([[ "$HOP" -gt 1 ]] && echo "192.168.$((SUBNET-1)).2")"
STA_GW="$([[ "$HOP" -gt 1 ]] && echo "192.168.$((SUBNET-1)).1")"

# 규정 도메인 명시 — KR 한도(20 dBm)까지 TX power 허용
iw reg set KR 2>/dev/null || true

# 인터페이스가 나타날 때까지 최대 20초 대기 (USB 동글 초기화 시간)
for _i in \$(seq 1 20); do
    ip link show "\$AP_IF" >/dev/null 2>&1 && break
    sleep 1
done

# NM/wpa_supplicant가 인터페이스를 점유하면 hostapd AP 모드 전환 불가
# → unmanaged 설정 후 wpa_supplicant 강제 종료 + down/up 사이클
nmcli device set "\$AP_IF" managed no 2>/dev/null || true
wpa_cli -i "\$AP_IF" terminate 2>/dev/null || true
pkill -f "wpa_supplicant.*\$AP_IF" 2>/dev/null || true
sleep 1
ip link set "\$AP_IF" down 2>/dev/null || true
sleep 1

# STA_IF: 다른 SSID로 잘못 붙는 것을 막기 위해 wpa_supplicant 재시작 강제
# (dhcpcd 훅 / 잔여 인스턴스가 글로벌 conf로 다른 네트워크에 붙는 경우 차단)
if [[ "\$HOP" -gt 1 && -n "\$STA_IF" && "\$STA_IF" != "\$AP_IF" ]]; then
    nmcli device set "\$STA_IF" managed no 2>/dev/null || true
    pkill -f "wpa_supplicant.*\$STA_IF" 2>/dev/null || true
    sleep 1
    ip link set "\$STA_IF" up 2>/dev/null || true
    systemctl restart "wpa_supplicant@\$STA_IF" 2>/dev/null || true

    # association 대기 (최대 15초)
    for _i in \$(seq 1 15); do
        iw dev "\$STA_IF" link 2>/dev/null | grep -q "Connected to" && break
        sleep 1
    done

    # 정적 IP 직접 부여 (dhcpcd 미적용 케이스 대비)
    # association은 됐지만 IP 없는 상태 → 수동 할당으로 복구
    ip addr flush dev "\$STA_IF" 2>/dev/null || true
    ip addr add "\${STA_STATIC_IP}/24" dev "\$STA_IF" 2>/dev/null || true
    # default route: 업스트림 GW로
    ip route del default 2>/dev/null || true
    ip route add default via "\$STA_GW" dev "\$STA_IF" 2>/dev/null || true

    # STA TX power 최대 (20 dBm = 2000 mBm, KR 한도)
    iw dev "\$STA_IF" set txpower fixed 2000 2>/dev/null || true
fi

EOF

    # --- AP_IF=ap0인 경우: 가상 인터페이스 재생성 (quoted EOF — 그대로 출력) ---
    if [[ "$AP_IF" == "ap0" ]]; then
        sudo tee -a /usr/local/bin/rpi-ap-boot.sh > /dev/null <<'EOF'
iw dev ap0 del 2>/dev/null || true
iw dev wlan0 interface add ap0 type __ap 2>/dev/null || true
EOF
    fi

    # --- AP 인터페이스 UP + IP 부여 + IP forward ---
    sudo tee -a /usr/local/bin/rpi-ap-boot.sh > /dev/null <<EOF
rfkill unblock wifi 2>/dev/null || true
ip link set "\$AP_IF" up 2>/dev/null || true
ip addr flush dev "\$AP_IF" 2>/dev/null || true
ip addr add "\${AP_IP}/24" dev "\$AP_IF" 2>/dev/null || true
sysctl -w net.ipv4.ip_forward=1 > /dev/null || true

# AP TX power 최대 — hostapd가 인터페이스 가져간 뒤에도 적용되도록 잠시 대기 후 설정
( sleep 5; iw dev "\$AP_IF" set txpower fixed 2000 2>/dev/null || true ) &
EOF

    # --- 다운스트림 라우트 (HOP < 3) ---
    if [[ "$HOP" -lt 3 ]]; then
        if [[ -z "$NEXT_HOP_IP" ]]; then
            echo "    [오류] NEXT_HOP_IP가 비어 있습니다 — boot.sh 라우트 생성 불가"
            exit 1
        fi
        local i SUBNET_ROUTE
        for i in $(seq $((HOP+1)) 3); do
            SUBNET_ROUTE="192.168.$((100+i)).0/24"
            echo "ip route replace ${SUBNET_ROUTE} via ${NEXT_HOP_IP} 2>/dev/null || true" \
                | sudo tee -a /usr/local/bin/rpi-ap-boot.sh > /dev/null
        done
    fi

    # --- HOP=1 NAT 규칙 ---
    if [[ "$HOP" -eq 1 ]]; then
        sudo tee -a /usr/local/bin/rpi-ap-boot.sh > /dev/null <<EOF
iptables -t nat -D POSTROUTING -o ${WAN_IF} -j MASQUERADE 2>/dev/null || true
iptables -D FORWARD -i ${AP_IF} -o ${WAN_IF} -j ACCEPT 2>/dev/null || true
iptables -D FORWARD -i ${WAN_IF} -o ${AP_IF} -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
iptables -t nat -A POSTROUTING -o ${WAN_IF} -j MASQUERADE 2>/dev/null || true
iptables -A FORWARD -i ${AP_IF} -o ${WAN_IF} -j ACCEPT 2>/dev/null || true
iptables -A FORWARD -i ${WAN_IF} -o ${AP_IF} -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
EOF
    fi

    # 개별 명령 실패가 서비스 전체를 막지 않도록 항상 0으로 종료
    echo "exit 0" | sudo tee -a /usr/local/bin/rpi-ap-boot.sh > /dev/null

    sudo chmod +x /usr/local/bin/rpi-ap-boot.sh
}
